<a href="https://colab.research.google.com/github/kiranmohan3236/Numpy/blob/main/18_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list =[1,2,3]

In [ ]:
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
arr = np.array(my_list)

In [ ]:
arr

array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace

In [ ]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### eye



*   Dealing with Algebra Problem
*   Number of rows is equal to number of columns
*   Have a diagonal of ones













In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### random - random numbers

In [ ]:
np.random.rand(5) #one dimension
#random sample for uniform distribution

array([0.48252229, 0.08985878, 0.02502124, 0.5560134 , 0.16576388])

In [ ]:
np.random.rand(5,5) #two dimension

array([[0.33189227, 0.93289273, 0.53517216, 0.58144443, 0.2621218 ],
       [0.39799217, 0.08559757, 0.91756641, 0.93080171, 0.25049289],
       [0.30799299, 0.79543484, 0.41584431, 0.78229338, 0.88488474],
       [0.32692769, 0.25005709, 0.27109288, 0.63956248, 0.18861253],
       [0.2876122 , 0.47511835, 0.26393849, 0.30457031, 0.37464702]])

In [ ]:
np.random.randn(2) #two random numbers

array([ 0.74513271, -0.16046994])

In [ ]:
np.random.randn(4,4)

array([[-1.48320013, -0.36508617,  1.47891539, -0.01383443],
       [ 0.57973827, -0.85576365, -1.69854097,  0.3117972 ],
       [ 0.21372798,  0.15536857, -2.09468053, -0.55099504],
       [-0.24011514, -0.6963654 ,  0.19777934, -0.87424626]])

In [ ]:
#random integers from a low to high
np.random.randint(1,100) #between 1 and 100 a random number

95

In [ ]:
np.random.randint(1,100,10)

array([62, 88, 76, 59,  9, 64, 46,  6, 37, 87])

### arange

In [ ]:
arr = np.arange(25)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0,50,10) #random integer between 0 to 50, a total of 10 numbers

In [ ]:
ranarr

array([24, 25, 47, 31,  7, 46, 15, 46,  6, 18])

### Reshape

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

array([24, 25, 47, 31,  7, 46, 15, 46,  6, 18])

### max, min

In [ ]:
ranarr

array([24, 25, 47, 31,  7, 46, 15, 46,  6, 18])

In [ ]:
ranarr.max()

47

In [ ]:
ranarr.min()

6

In [ ]:
ranarr.argmax() #index value of the max value

2

In [ ]:
ranarr.argmin() #index location of the min value

8

In [ ]:
arr.shape #it will give you the shape, here it is indicating that it is a one dimension array

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#now checking the shape
#it give a two dimensional array

In [ ]:
arr.shape #it gives a two dimensional array

(5, 5)

### data type

In [ ]:
arr.dtype

dtype('int64')

### Extra

In [ ]:
# it you  don't want to write np.random you can just say randint afterwards

In [ ]:
from numpy.random import randint

In [ ]:
randint(2,10)

4