<a href="https://colab.research.google.com/github/kiranmohan3236/Numpy/blob/main/20_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6] #same output you will get

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[0:6] #same output you will get

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr = np.arange(0,11) #reseting the array or re writing the array arr as a new one deleting the old 100 broadcasting one

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slices in array

In [26]:
slice_of_arr = arr[0:6]

In [27]:
slice_of_arr #same output

array([0, 1, 2, 3, 4, 5])

In [28]:
slice_of_arr[:] #same output

array([0, 1, 2, 3, 4, 5])

In [29]:
slice_of_arr[:] = 99

In [30]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [31]:
slice_of_arr #it changes on the original array also

array([99, 99, 99, 99, 99, 99])

In [34]:
arr #it changes the original array, its not a view

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### copy

In [35]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [36]:
arr_copy = arr.copy()

In [37]:
arr_copy[:] = 100

In [38]:
arr_copy #only copy is affected

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [39]:
arr #original value still unaffected

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])