<a href="https://colab.research.google.com/github/kiranmohan3236/Numpy/blob/main/Section%205%2020_2_D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 2 D

In [2]:
import numpy as np

In [3]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
arr_2d[0]

array([ 5, 10, 15])

In [6]:
arr_2d[1][1]

25

In [7]:
arr_2d[2][1]

40

In [8]:
arr_2d[1,2] #same

30

In [9]:
arr_2d[1][2] #same

30

In [10]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [11]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [15]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [20]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [21]:
arr = np.arange(1,11)

In [22]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
bool_arr = arr > 5

In [25]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
arr[bool_arr] #get the numbers where the numbers are greater than 5

array([ 6,  7,  8,  9, 10])

In [27]:
#another method
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [29]:
arr[arr<3]

array([1, 2])

In [30]:
arr_2d = np.arange(50).reshape(5,10)

In [31]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
arr_2d[1:3,4:6]

array([[14, 15],
       [24, 25]])

In [42]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [43]:
arr_2d[:3,3:]

array([[ 3,  4,  5,  6,  7,  8,  9],
       [13, 14, 15, 16, 17, 18, 19],
       [23, 24, 25, 26, 27, 28, 29]])